#!/bin/bash

mv -f /usr/bin/google-chrome-stable /usr/bin/google-chrome-stable.orig

echo '#!/bin/bash
exec nosync-browser $(cat ~/.config/nosync-browser-flags/chrome 2> /dev/null) /usr/bin/google-chrome-stable.orig "$@"' > /usr/bin/google-chrome-stable

chmod +x /usr/bin/google-chrome-stable
